name: Deploy Website

on:
  push:
    branches:
      - main

env:
  SURGE_DOMAIN_STORE: ${{ secrets.SURGE_DOMAIN_STORE }}
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying apps
    environment:
      name: test
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx nx deploy store
      - run: npx nx deploy api